package io.github.xdiamond.persistence;

import io.github.xdiamond.domain.GroupRole;
import io.github.xdiamond.domain.GroupRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GroupRoleMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table group_roles
   * @mbggenerated
   */
  int countByExample(GroupRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table group_roles
   * @mbggenerated
   */
  int deleteByExample(GroupRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table group_roles
   * @mbggenerated
   */
  int deleteByPrimaryKey(@Param("groupId") Integer groupId, @Param("roleId") Integer roleId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table group_roles
   * @mbggenerated
   */
  int insert(GroupRole record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table group_roles
   * @mbggenerated
   */
  int insertSelective(GroupRole record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table group_roles
   * @mbggenerated
   */
  List<GroupRole> selectByExample(GroupRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table group_roles
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") GroupRole record,
      @Param("example") GroupRoleExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table group_roles
   * @mbggenerated
   */
  int updateByExample(@Param("record") GroupRole record, @Param("example") GroupRoleExample example);
}