package io.github.xdiamond.persistence;

import io.github.xdiamond.domain.User;
import io.github.xdiamond.domain.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int countByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int deleteByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int deleteByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int insert(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int insertSelective(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  List<User> selectByExample(UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  User selectByPrimaryKey(Integer id);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int updateByExample(@Param("record") User record, @Param("example") UserExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(User record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user
   * @mbggenerated
   */
  int updateByPrimaryKey(User record);
}