package io.github.xdiamond.persistence;

import io.github.xdiamond.domain.UserGroup;
import io.github.xdiamond.domain.UserGroupExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserGroupMapper {

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int countByExample(UserGroupExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int deleteByExample(UserGroupExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int deleteByPrimaryKey(@Param("userId") Integer userId, @Param("groupId") Integer groupId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int insert(UserGroup record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int insertSelective(UserGroup record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  List<UserGroup> selectByExample(UserGroupExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  UserGroup selectByPrimaryKey(@Param("userId") Integer userId, @Param("groupId") Integer groupId);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int updateByExampleSelective(@Param("record") UserGroup record,
      @Param("example") UserGroupExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int updateByExample(@Param("record") UserGroup record, @Param("example") UserGroupExample example);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int updateByPrimaryKeySelective(UserGroup record);

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table user_groups
   * @mbggenerated
   */
  int updateByPrimaryKey(UserGroup record);
}