package io.github.xdiamond.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ConfigExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table config
   * @mbggenerated
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table config
   * @mbggenerated
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table config
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public ConfigExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table config
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table config
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Integer value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Integer value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Integer value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Integer value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Integer value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Integer value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Integer> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Integer> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Integer value1, Integer value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Integer value1, Integer value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andProfileIdIsNull() {
      addCriterion("profileId is null");
      return (Criteria) this;
    }

    public Criteria andProfileIdIsNotNull() {
      addCriterion("profileId is not null");
      return (Criteria) this;
    }

    public Criteria andProfileIdEqualTo(Integer value) {
      addCriterion("profileId =", value, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdNotEqualTo(Integer value) {
      addCriterion("profileId <>", value, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdGreaterThan(Integer value) {
      addCriterion("profileId >", value, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdGreaterThanOrEqualTo(Integer value) {
      addCriterion("profileId >=", value, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdLessThan(Integer value) {
      addCriterion("profileId <", value, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdLessThanOrEqualTo(Integer value) {
      addCriterion("profileId <=", value, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdIn(List<Integer> values) {
      addCriterion("profileId in", values, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdNotIn(List<Integer> values) {
      addCriterion("profileId not in", values, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdBetween(Integer value1, Integer value2) {
      addCriterion("profileId between", value1, value2, "profileId");
      return (Criteria) this;
    }

    public Criteria andProfileIdNotBetween(Integer value1, Integer value2) {
      addCriterion("profileId not between", value1, value2, "profileId");
      return (Criteria) this;
    }

    public Criteria andKeyIsNull() {
      addCriterion("`key` is null");
      return (Criteria) this;
    }

    public Criteria andKeyIsNotNull() {
      addCriterion("`key` is not null");
      return (Criteria) this;
    }

    public Criteria andKeyEqualTo(String value) {
      addCriterion("`key` =", value, "key");
      return (Criteria) this;
    }

    public Criteria andKeyNotEqualTo(String value) {
      addCriterion("`key` <>", value, "key");
      return (Criteria) this;
    }

    public Criteria andKeyGreaterThan(String value) {
      addCriterion("`key` >", value, "key");
      return (Criteria) this;
    }

    public Criteria andKeyGreaterThanOrEqualTo(String value) {
      addCriterion("`key` >=", value, "key");
      return (Criteria) this;
    }

    public Criteria andKeyLessThan(String value) {
      addCriterion("`key` <", value, "key");
      return (Criteria) this;
    }

    public Criteria andKeyLessThanOrEqualTo(String value) {
      addCriterion("`key` <=", value, "key");
      return (Criteria) this;
    }

    public Criteria andKeyLike(String value) {
      addCriterion("`key` like", value, "key");
      return (Criteria) this;
    }

    public Criteria andKeyNotLike(String value) {
      addCriterion("`key` not like", value, "key");
      return (Criteria) this;
    }

    public Criteria andKeyIn(List<String> values) {
      addCriterion("`key` in", values, "key");
      return (Criteria) this;
    }

    public Criteria andKeyNotIn(List<String> values) {
      addCriterion("`key` not in", values, "key");
      return (Criteria) this;
    }

    public Criteria andKeyBetween(String value1, String value2) {
      addCriterion("`key` between", value1, value2, "key");
      return (Criteria) this;
    }

    public Criteria andKeyNotBetween(String value1, String value2) {
      addCriterion("`key` not between", value1, value2, "key");
      return (Criteria) this;
    }

    public Criteria andValueIsNull() {
      addCriterion("`value` is null");
      return (Criteria) this;
    }

    public Criteria andValueIsNotNull() {
      addCriterion("`value` is not null");
      return (Criteria) this;
    }

    public Criteria andValueEqualTo(String value) {
      addCriterion("`value` =", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueNotEqualTo(String value) {
      addCriterion("`value` <>", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueGreaterThan(String value) {
      addCriterion("`value` >", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueGreaterThanOrEqualTo(String value) {
      addCriterion("`value` >=", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueLessThan(String value) {
      addCriterion("`value` <", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueLessThanOrEqualTo(String value) {
      addCriterion("`value` <=", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueLike(String value) {
      addCriterion("`value` like", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueNotLike(String value) {
      addCriterion("`value` not like", value, "value");
      return (Criteria) this;
    }

    public Criteria andValueIn(List<String> values) {
      addCriterion("`value` in", values, "value");
      return (Criteria) this;
    }

    public Criteria andValueNotIn(List<String> values) {
      addCriterion("`value` not in", values, "value");
      return (Criteria) this;
    }

    public Criteria andValueBetween(String value1, String value2) {
      addCriterion("`value` between", value1, value2, "value");
      return (Criteria) this;
    }

    public Criteria andValueNotBetween(String value1, String value2) {
      addCriterion("`value` not between", value1, value2, "value");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueIsNull() {
      addCriterion("lastVersionValue is null");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueIsNotNull() {
      addCriterion("lastVersionValue is not null");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueEqualTo(String value) {
      addCriterion("lastVersionValue =", value, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueNotEqualTo(String value) {
      addCriterion("lastVersionValue <>", value, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueGreaterThan(String value) {
      addCriterion("lastVersionValue >", value, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueGreaterThanOrEqualTo(String value) {
      addCriterion("lastVersionValue >=", value, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueLessThan(String value) {
      addCriterion("lastVersionValue <", value, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueLessThanOrEqualTo(String value) {
      addCriterion("lastVersionValue <=", value, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueLike(String value) {
      addCriterion("lastVersionValue like", value, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueNotLike(String value) {
      addCriterion("lastVersionValue not like", value, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueIn(List<String> values) {
      addCriterion("lastVersionValue in", values, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueNotIn(List<String> values) {
      addCriterion("lastVersionValue not in", values, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueBetween(String value1, String value2) {
      addCriterion("lastVersionValue between", value1, value2, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andLastVersionValueNotBetween(String value1, String value2) {
      addCriterion("lastVersionValue not between", value1, value2, "lastVersionValue");
      return (Criteria) this;
    }

    public Criteria andDescriptionIsNull() {
      addCriterion("description is null");
      return (Criteria) this;
    }

    public Criteria andDescriptionIsNotNull() {
      addCriterion("description is not null");
      return (Criteria) this;
    }

    public Criteria andDescriptionEqualTo(String value) {
      addCriterion("description =", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotEqualTo(String value) {
      addCriterion("description <>", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionGreaterThan(String value) {
      addCriterion("description >", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
      addCriterion("description >=", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLessThan(String value) {
      addCriterion("description <", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLessThanOrEqualTo(String value) {
      addCriterion("description <=", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLike(String value) {
      addCriterion("description like", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotLike(String value) {
      addCriterion("description not like", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionIn(List<String> values) {
      addCriterion("description in", values, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotIn(List<String> values) {
      addCriterion("description not in", values, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionBetween(String value1, String value2) {
      addCriterion("description between", value1, value2, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotBetween(String value1, String value2) {
      addCriterion("description not between", value1, value2, "description");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNull() {
      addCriterion("createTime is null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIsNotNull() {
      addCriterion("createTime is not null");
      return (Criteria) this;
    }

    public Criteria andCreateTimeEqualTo(Date value) {
      addCriterion("createTime =", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotEqualTo(Date value) {
      addCriterion("createTime <>", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThan(Date value) {
      addCriterion("createTime >", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("createTime >=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThan(Date value) {
      addCriterion("createTime <", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
      addCriterion("createTime <=", value, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeIn(List<Date> values) {
      addCriterion("createTime in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotIn(List<Date> values) {
      addCriterion("createTime not in", values, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeBetween(Date value1, Date value2) {
      addCriterion("createTime between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
      addCriterion("createTime not between", value1, value2, "createTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNull() {
      addCriterion("updateTime is null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIsNotNull() {
      addCriterion("updateTime is not null");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeEqualTo(Date value) {
      addCriterion("updateTime =", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotEqualTo(Date value) {
      addCriterion("updateTime <>", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThan(Date value) {
      addCriterion("updateTime >", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
      addCriterion("updateTime >=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThan(Date value) {
      addCriterion("updateTime <", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
      addCriterion("updateTime <=", value, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeIn(List<Date> values) {
      addCriterion("updateTime in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotIn(List<Date> values) {
      addCriterion("updateTime not in", values, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeBetween(Date value1, Date value2) {
      addCriterion("updateTime between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
      addCriterion("updateTime not between", value1, value2, "updateTime");
      return (Criteria) this;
    }

    public Criteria andCreateUserIsNull() {
      addCriterion("`createUser` is null");
      return (Criteria) this;
    }

    public Criteria andCreateUserIsNotNull() {
      addCriterion("`createUser` is not null");
      return (Criteria) this;
    }

    public Criteria andCreateUserEqualTo(String value) {
      addCriterion("`createUser` =", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserNotEqualTo(String value) {
      addCriterion("`createUser` <>", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserGreaterThan(String value) {
      addCriterion("`createUser` >", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
      addCriterion("`createUser` >=", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserLessThan(String value) {
      addCriterion("`createUser` <", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserLessThanOrEqualTo(String value) {
      addCriterion("`createUser` <=", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserLike(String value) {
      addCriterion("`createUser` like", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserNotLike(String value) {
      addCriterion("`createUser` not like", value, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserIn(List<String> values) {
      addCriterion("`createUser` in", values, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserNotIn(List<String> values) {
      addCriterion("`createUser` not in", values, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserBetween(String value1, String value2) {
      addCriterion("`createUser` between", value1, value2, "createUser");
      return (Criteria) this;
    }

    public Criteria andCreateUserNotBetween(String value1, String value2) {
      addCriterion("`createUser` not between", value1, value2, "createUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserIsNull() {
      addCriterion("updateUser is null");
      return (Criteria) this;
    }

    public Criteria andUpdateUserIsNotNull() {
      addCriterion("updateUser is not null");
      return (Criteria) this;
    }

    public Criteria andUpdateUserEqualTo(String value) {
      addCriterion("updateUser =", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserNotEqualTo(String value) {
      addCriterion("updateUser <>", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserGreaterThan(String value) {
      addCriterion("updateUser >", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
      addCriterion("updateUser >=", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserLessThan(String value) {
      addCriterion("updateUser <", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserLessThanOrEqualTo(String value) {
      addCriterion("updateUser <=", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserLike(String value) {
      addCriterion("updateUser like", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserNotLike(String value) {
      addCriterion("updateUser not like", value, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserIn(List<String> values) {
      addCriterion("updateUser in", values, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserNotIn(List<String> values) {
      addCriterion("updateUser not in", values, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserBetween(String value1, String value2) {
      addCriterion("updateUser between", value1, value2, "updateUser");
      return (Criteria) this;
    }

    public Criteria andUpdateUserNotBetween(String value1, String value2) {
      addCriterion("updateUser not between", value1, value2, "updateUser");
      return (Criteria) this;
    }

    public Criteria andVersionIsNull() {
      addCriterion("version is null");
      return (Criteria) this;
    }

    public Criteria andVersionIsNotNull() {
      addCriterion("version is not null");
      return (Criteria) this;
    }

    public Criteria andVersionEqualTo(Integer value) {
      addCriterion("version =", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotEqualTo(Integer value) {
      addCriterion("version <>", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionGreaterThan(Integer value) {
      addCriterion("version >", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionGreaterThanOrEqualTo(Integer value) {
      addCriterion("version >=", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionLessThan(Integer value) {
      addCriterion("version <", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionLessThanOrEqualTo(Integer value) {
      addCriterion("version <=", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionIn(List<Integer> values) {
      addCriterion("version in", values, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotIn(List<Integer> values) {
      addCriterion("version not in", values, "version");
      return (Criteria) this;
    }

    public Criteria andVersionBetween(Integer value1, Integer value2) {
      addCriterion("version between", value1, value2, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotBetween(Integer value1, Integer value2) {
      addCriterion("version not between", value1, value2, "version");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table config
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table config
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}