package io.github.xdiamond.domain;

import java.util.Date;
import java.io.Serializable;

public class Config implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.id
   * @mbggenerated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.profileId
   * @mbggenerated
   */
  private Integer profileId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.key
   * @mbggenerated
   */
  private String key;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.value
   * @mbggenerated
   */
  private String value;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.lastVersionValue
   * @mbggenerated
   */
  private String lastVersionValue;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.description
   * @mbggenerated
   */
  private String description;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.createTime
   * @mbggenerated
   */
  private Date createTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.updateTime
   * @mbggenerated
   */
  private Date updateTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.createUser
   * @mbggenerated
   */
  private String createUser;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.updateUser
   * @mbggenerated
   */
  private String updateUser;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column config.version
   * @mbggenerated
   */
  private Integer version;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table config
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.id
   * @return  the value of config.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.id
   * @param id  the value for config.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.profileId
   * @return  the value of config.profileId
   * @mbggenerated
   */
  public Integer getProfileId() {
    return profileId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.profileId
   * @param profileId  the value for config.profileId
   * @mbggenerated
   */
  public void setProfileId(Integer profileId) {
    this.profileId = profileId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.key
   * @return  the value of config.key
   * @mbggenerated
   */
  public String getKey() {
    return key;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.key
   * @param key  the value for config.key
   * @mbggenerated
   */
  public void setKey(String key) {
    this.key = key;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.value
   * @return  the value of config.value
   * @mbggenerated
   */
  public String getValue() {
    return value;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.value
   * @param value  the value for config.value
   * @mbggenerated
   */
  public void setValue(String value) {
    this.value = value;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.lastVersionValue
   * @return  the value of config.lastVersionValue
   * @mbggenerated
   */
  public String getLastVersionValue() {
    return lastVersionValue;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.lastVersionValue
   * @param lastVersionValue  the value for config.lastVersionValue
   * @mbggenerated
   */
  public void setLastVersionValue(String lastVersionValue) {
    this.lastVersionValue = lastVersionValue;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.description
   * @return  the value of config.description
   * @mbggenerated
   */
  public String getDescription() {
    return description;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.description
   * @param description  the value for config.description
   * @mbggenerated
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.createTime
   * @return  the value of config.createTime
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.createTime
   * @param createTime  the value for config.createTime
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.updateTime
   * @return  the value of config.updateTime
   * @mbggenerated
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.updateTime
   * @param updateTime  the value for config.updateTime
   * @mbggenerated
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.createUser
   * @return  the value of config.createUser
   * @mbggenerated
   */
  public String getCreateUser() {
    return createUser;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.createUser
   * @param createUser  the value for config.createUser
   * @mbggenerated
   */
  public void setCreateUser(String createUser) {
    this.createUser = createUser;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.updateUser
   * @return  the value of config.updateUser
   * @mbggenerated
   */
  public String getUpdateUser() {
    return updateUser;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.updateUser
   * @param updateUser  the value for config.updateUser
   * @mbggenerated
   */
  public void setUpdateUser(String updateUser) {
    this.updateUser = updateUser;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column config.version
   * @return  the value of config.version
   * @mbggenerated
   */
  public Integer getVersion() {
    return version;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column config.version
   * @param version  the value for config.version
   * @mbggenerated
   */
  public void setVersion(Integer version) {
    this.version = version;
  }
}