package io.github.xdiamond.domain;

import java.io.Serializable;

public class Dependency implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dependency.id
   * @mbggenerated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dependency.projectId
   * @mbggenerated
   */
  private Integer projectId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column dependency.dependencyProjectId
   * @mbggenerated
   */
  private Integer dependencyProjectId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table dependency
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dependency.id
   * @return  the value of dependency.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dependency.id
   * @param id  the value for dependency.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dependency.projectId
   * @return  the value of dependency.projectId
   * @mbggenerated
   */
  public Integer getProjectId() {
    return projectId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dependency.projectId
   * @param projectId  the value for dependency.projectId
   * @mbggenerated
   */
  public void setProjectId(Integer projectId) {
    this.projectId = projectId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column dependency.dependencyProjectId
   * @return  the value of dependency.dependencyProjectId
   * @mbggenerated
   */
  public Integer getDependencyProjectId() {
    return dependencyProjectId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column dependency.dependencyProjectId
   * @param dependencyProjectId  the value for dependency.dependencyProjectId
   * @mbggenerated
   */
  public void setDependencyProjectId(Integer dependencyProjectId) {
    this.dependencyProjectId = dependencyProjectId;
  }
}