package io.github.xdiamond.domain;

import java.io.Serializable;

public class Permission implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column permission.id
   * @mbggenerated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column permission.permissionStr
   * @mbggenerated
   */
  private String permissionStr;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column permission.description
   * @mbggenerated
   */
  private String description;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table permission
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column permission.id
   * @return  the value of permission.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column permission.id
   * @param id  the value for permission.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column permission.permissionStr
   * @return  the value of permission.permissionStr
   * @mbggenerated
   */
  public String getPermissionStr() {
    return permissionStr;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column permission.permissionStr
   * @param permissionStr  the value for permission.permissionStr
   * @mbggenerated
   */
  public void setPermissionStr(String permissionStr) {
    this.permissionStr = permissionStr;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column permission.description
   * @return  the value of permission.description
   * @mbggenerated
   */
  public String getDescription() {
    return description;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column permission.description
   * @param description  the value for permission.description
   * @mbggenerated
   */
  public void setDescription(String description) {
    this.description = description;
  }
}