package io.github.xdiamond.domain;

import java.util.ArrayList;
import java.util.List;

public class ProjectExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table project
   * @mbggenerated
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table project
   * @mbggenerated
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table project
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public ProjectExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table project
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table project
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andIdIsNull() {
      addCriterion("id is null");
      return (Criteria) this;
    }

    public Criteria andIdIsNotNull() {
      addCriterion("id is not null");
      return (Criteria) this;
    }

    public Criteria andIdEqualTo(Integer value) {
      addCriterion("id =", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotEqualTo(Integer value) {
      addCriterion("id <>", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThan(Integer value) {
      addCriterion("id >", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdGreaterThanOrEqualTo(Integer value) {
      addCriterion("id >=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThan(Integer value) {
      addCriterion("id <", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdLessThanOrEqualTo(Integer value) {
      addCriterion("id <=", value, "id");
      return (Criteria) this;
    }

    public Criteria andIdIn(List<Integer> values) {
      addCriterion("id in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotIn(List<Integer> values) {
      addCriterion("id not in", values, "id");
      return (Criteria) this;
    }

    public Criteria andIdBetween(Integer value1, Integer value2) {
      addCriterion("id between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andIdNotBetween(Integer value1, Integer value2) {
      addCriterion("id not between", value1, value2, "id");
      return (Criteria) this;
    }

    public Criteria andGroupIdIsNull() {
      addCriterion("groupId is null");
      return (Criteria) this;
    }

    public Criteria andGroupIdIsNotNull() {
      addCriterion("groupId is not null");
      return (Criteria) this;
    }

    public Criteria andGroupIdEqualTo(String value) {
      addCriterion("groupId =", value, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdNotEqualTo(String value) {
      addCriterion("groupId <>", value, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdGreaterThan(String value) {
      addCriterion("groupId >", value, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdGreaterThanOrEqualTo(String value) {
      addCriterion("groupId >=", value, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdLessThan(String value) {
      addCriterion("groupId <", value, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdLessThanOrEqualTo(String value) {
      addCriterion("groupId <=", value, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdLike(String value) {
      addCriterion("groupId like", value, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdNotLike(String value) {
      addCriterion("groupId not like", value, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdIn(List<String> values) {
      addCriterion("groupId in", values, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdNotIn(List<String> values) {
      addCriterion("groupId not in", values, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdBetween(String value1, String value2) {
      addCriterion("groupId between", value1, value2, "groupId");
      return (Criteria) this;
    }

    public Criteria andGroupIdNotBetween(String value1, String value2) {
      addCriterion("groupId not between", value1, value2, "groupId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdIsNull() {
      addCriterion("artifactId is null");
      return (Criteria) this;
    }

    public Criteria andArtifactIdIsNotNull() {
      addCriterion("artifactId is not null");
      return (Criteria) this;
    }

    public Criteria andArtifactIdEqualTo(String value) {
      addCriterion("artifactId =", value, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdNotEqualTo(String value) {
      addCriterion("artifactId <>", value, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdGreaterThan(String value) {
      addCriterion("artifactId >", value, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdGreaterThanOrEqualTo(String value) {
      addCriterion("artifactId >=", value, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdLessThan(String value) {
      addCriterion("artifactId <", value, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdLessThanOrEqualTo(String value) {
      addCriterion("artifactId <=", value, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdLike(String value) {
      addCriterion("artifactId like", value, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdNotLike(String value) {
      addCriterion("artifactId not like", value, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdIn(List<String> values) {
      addCriterion("artifactId in", values, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdNotIn(List<String> values) {
      addCriterion("artifactId not in", values, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdBetween(String value1, String value2) {
      addCriterion("artifactId between", value1, value2, "artifactId");
      return (Criteria) this;
    }

    public Criteria andArtifactIdNotBetween(String value1, String value2) {
      addCriterion("artifactId not between", value1, value2, "artifactId");
      return (Criteria) this;
    }

    public Criteria andVersionIsNull() {
      addCriterion("version is null");
      return (Criteria) this;
    }

    public Criteria andVersionIsNotNull() {
      addCriterion("version is not null");
      return (Criteria) this;
    }

    public Criteria andVersionEqualTo(String value) {
      addCriterion("version =", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotEqualTo(String value) {
      addCriterion("version <>", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionGreaterThan(String value) {
      addCriterion("version >", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionGreaterThanOrEqualTo(String value) {
      addCriterion("version >=", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionLessThan(String value) {
      addCriterion("version <", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionLessThanOrEqualTo(String value) {
      addCriterion("version <=", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionLike(String value) {
      addCriterion("version like", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotLike(String value) {
      addCriterion("version not like", value, "version");
      return (Criteria) this;
    }

    public Criteria andVersionIn(List<String> values) {
      addCriterion("version in", values, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotIn(List<String> values) {
      addCriterion("version not in", values, "version");
      return (Criteria) this;
    }

    public Criteria andVersionBetween(String value1, String value2) {
      addCriterion("version between", value1, value2, "version");
      return (Criteria) this;
    }

    public Criteria andVersionNotBetween(String value1, String value2) {
      addCriterion("version not between", value1, value2, "version");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupIsNull() {
      addCriterion("ownerGroup is null");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupIsNotNull() {
      addCriterion("ownerGroup is not null");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupEqualTo(Integer value) {
      addCriterion("ownerGroup =", value, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupNotEqualTo(Integer value) {
      addCriterion("ownerGroup <>", value, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupGreaterThan(Integer value) {
      addCriterion("ownerGroup >", value, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupGreaterThanOrEqualTo(Integer value) {
      addCriterion("ownerGroup >=", value, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupLessThan(Integer value) {
      addCriterion("ownerGroup <", value, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupLessThanOrEqualTo(Integer value) {
      addCriterion("ownerGroup <=", value, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupIn(List<Integer> values) {
      addCriterion("ownerGroup in", values, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupNotIn(List<Integer> values) {
      addCriterion("ownerGroup not in", values, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupBetween(Integer value1, Integer value2) {
      addCriterion("ownerGroup between", value1, value2, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andOwnerGroupNotBetween(Integer value1, Integer value2) {
      addCriterion("ownerGroup not between", value1, value2, "ownerGroup");
      return (Criteria) this;
    }

    public Criteria andDescriptionIsNull() {
      addCriterion("description is null");
      return (Criteria) this;
    }

    public Criteria andDescriptionIsNotNull() {
      addCriterion("description is not null");
      return (Criteria) this;
    }

    public Criteria andDescriptionEqualTo(String value) {
      addCriterion("description =", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotEqualTo(String value) {
      addCriterion("description <>", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionGreaterThan(String value) {
      addCriterion("description >", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
      addCriterion("description >=", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLessThan(String value) {
      addCriterion("description <", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLessThanOrEqualTo(String value) {
      addCriterion("description <=", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionLike(String value) {
      addCriterion("description like", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotLike(String value) {
      addCriterion("description not like", value, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionIn(List<String> values) {
      addCriterion("description in", values, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotIn(List<String> values) {
      addCriterion("description not in", values, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionBetween(String value1, String value2) {
      addCriterion("description between", value1, value2, "description");
      return (Criteria) this;
    }

    public Criteria andDescriptionNotBetween(String value1, String value2) {
      addCriterion("description not between", value1, value2, "description");
      return (Criteria) this;
    }

    public Criteria andBPublicIsNull() {
      addCriterion("bPublic is null");
      return (Criteria) this;
    }

    public Criteria andBPublicIsNotNull() {
      addCriterion("bPublic is not null");
      return (Criteria) this;
    }

    public Criteria andBPublicEqualTo(Boolean value) {
      addCriterion("bPublic =", value, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicNotEqualTo(Boolean value) {
      addCriterion("bPublic <>", value, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicGreaterThan(Boolean value) {
      addCriterion("bPublic >", value, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicGreaterThanOrEqualTo(Boolean value) {
      addCriterion("bPublic >=", value, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicLessThan(Boolean value) {
      addCriterion("bPublic <", value, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicLessThanOrEqualTo(Boolean value) {
      addCriterion("bPublic <=", value, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicIn(List<Boolean> values) {
      addCriterion("bPublic in", values, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicNotIn(List<Boolean> values) {
      addCriterion("bPublic not in", values, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicBetween(Boolean value1, Boolean value2) {
      addCriterion("bPublic between", value1, value2, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBPublicNotBetween(Boolean value1, Boolean value2) {
      addCriterion("bPublic not between", value1, value2, "bPublic");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyIsNull() {
      addCriterion("bAllowDependency is null");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyIsNotNull() {
      addCriterion("bAllowDependency is not null");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyEqualTo(Boolean value) {
      addCriterion("bAllowDependency =", value, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyNotEqualTo(Boolean value) {
      addCriterion("bAllowDependency <>", value, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyGreaterThan(Boolean value) {
      addCriterion("bAllowDependency >", value, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyGreaterThanOrEqualTo(Boolean value) {
      addCriterion("bAllowDependency >=", value, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyLessThan(Boolean value) {
      addCriterion("bAllowDependency <", value, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyLessThanOrEqualTo(Boolean value) {
      addCriterion("bAllowDependency <=", value, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyIn(List<Boolean> values) {
      addCriterion("bAllowDependency in", values, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyNotIn(List<Boolean> values) {
      addCriterion("bAllowDependency not in", values, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyBetween(Boolean value1, Boolean value2) {
      addCriterion("bAllowDependency between", value1, value2, "bAllowDependency");
      return (Criteria) this;
    }

    public Criteria andBAllowDependencyNotBetween(Boolean value1, Boolean value2) {
      addCriterion("bAllowDependency not between", value1, value2, "bAllowDependency");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table project
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table project
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}