package io.github.xdiamond.domain;

import java.util.ArrayList;
import java.util.List;

public class RolePermissionExample {
    /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table role_permissions
   * @mbggenerated
   */
  protected String orderByClause;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table role_permissions
   * @mbggenerated
   */
  protected boolean distinct;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table role_permissions
   * @mbggenerated
   */
  protected List<Criteria> oredCriteria;

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public RolePermissionExample() {
    oredCriteria = new ArrayList<Criteria>();
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public void setOrderByClause(String orderByClause) {
    this.orderByClause = orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public String getOrderByClause() {
    return orderByClause;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public void setDistinct(boolean distinct) {
    this.distinct = distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public boolean isDistinct() {
    return distinct;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public List<Criteria> getOredCriteria() {
    return oredCriteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public void or(Criteria criteria) {
    oredCriteria.add(criteria);
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public Criteria or() {
    Criteria criteria = createCriteriaInternal();
    oredCriteria.add(criteria);
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public Criteria createCriteria() {
    Criteria criteria = createCriteriaInternal();
    if (oredCriteria.size() == 0) {
      oredCriteria.add(criteria);
    }
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  protected Criteria createCriteriaInternal() {
    Criteria criteria = new Criteria();
    return criteria;
  }

  /**
   * This method was generated by MyBatis Generator. This method corresponds to the database table role_permissions
   * @mbggenerated
   */
  public void clear() {
    oredCriteria.clear();
    orderByClause = null;
    distinct = false;
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table role_permissions
   * @mbggenerated
   */
  protected abstract static class GeneratedCriteria {
    protected List<Criterion> criteria;

    protected GeneratedCriteria() {
      super();
      criteria = new ArrayList<Criterion>();
    }

    public boolean isValid() {
      return criteria.size() > 0;
    }

    public List<Criterion> getAllCriteria() {
      return criteria;
    }

    public List<Criterion> getCriteria() {
      return criteria;
    }

    protected void addCriterion(String condition) {
      if (condition == null) {
        throw new RuntimeException("Value for condition cannot be null");
      }
      criteria.add(new Criterion(condition));
    }

    protected void addCriterion(String condition, Object value, String property) {
      if (value == null) {
        throw new RuntimeException("Value for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value));
    }

    protected void addCriterion(String condition, Object value1, Object value2, String property) {
      if (value1 == null || value2 == null) {
        throw new RuntimeException("Between values for " + property + " cannot be null");
      }
      criteria.add(new Criterion(condition, value1, value2));
    }

    public Criteria andRoleIdIsNull() {
      addCriterion("roleId is null");
      return (Criteria) this;
    }

    public Criteria andRoleIdIsNotNull() {
      addCriterion("roleId is not null");
      return (Criteria) this;
    }

    public Criteria andRoleIdEqualTo(Integer value) {
      addCriterion("roleId =", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdNotEqualTo(Integer value) {
      addCriterion("roleId <>", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdGreaterThan(Integer value) {
      addCriterion("roleId >", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdGreaterThanOrEqualTo(Integer value) {
      addCriterion("roleId >=", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdLessThan(Integer value) {
      addCriterion("roleId <", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdLessThanOrEqualTo(Integer value) {
      addCriterion("roleId <=", value, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdIn(List<Integer> values) {
      addCriterion("roleId in", values, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdNotIn(List<Integer> values) {
      addCriterion("roleId not in", values, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdBetween(Integer value1, Integer value2) {
      addCriterion("roleId between", value1, value2, "roleId");
      return (Criteria) this;
    }

    public Criteria andRoleIdNotBetween(Integer value1, Integer value2) {
      addCriterion("roleId not between", value1, value2, "roleId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdIsNull() {
      addCriterion("permissionId is null");
      return (Criteria) this;
    }

    public Criteria andPermissionIdIsNotNull() {
      addCriterion("permissionId is not null");
      return (Criteria) this;
    }

    public Criteria andPermissionIdEqualTo(Integer value) {
      addCriterion("permissionId =", value, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdNotEqualTo(Integer value) {
      addCriterion("permissionId <>", value, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdGreaterThan(Integer value) {
      addCriterion("permissionId >", value, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdGreaterThanOrEqualTo(Integer value) {
      addCriterion("permissionId >=", value, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdLessThan(Integer value) {
      addCriterion("permissionId <", value, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdLessThanOrEqualTo(Integer value) {
      addCriterion("permissionId <=", value, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdIn(List<Integer> values) {
      addCriterion("permissionId in", values, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdNotIn(List<Integer> values) {
      addCriterion("permissionId not in", values, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdBetween(Integer value1, Integer value2) {
      addCriterion("permissionId between", value1, value2, "permissionId");
      return (Criteria) this;
    }

    public Criteria andPermissionIdNotBetween(Integer value1, Integer value2) {
      addCriterion("permissionId not between", value1, value2, "permissionId");
      return (Criteria) this;
    }
  }

  /**
   * This class was generated by MyBatis Generator. This class corresponds to the database table role_permissions
   * @mbggenerated
   */
  public static class Criterion {
    private String condition;
    private Object value;
    private Object secondValue;
    private boolean noValue;
    private boolean singleValue;
    private boolean betweenValue;
    private boolean listValue;
    private String typeHandler;

    public String getCondition() {
      return condition;
    }

    public Object getValue() {
      return value;
    }

    public Object getSecondValue() {
      return secondValue;
    }

    public boolean isNoValue() {
      return noValue;
    }

    public boolean isSingleValue() {
      return singleValue;
    }

    public boolean isBetweenValue() {
      return betweenValue;
    }

    public boolean isListValue() {
      return listValue;
    }

    public String getTypeHandler() {
      return typeHandler;
    }

    protected Criterion(String condition) {
      super();
      this.condition = condition;
      this.typeHandler = null;
      this.noValue = true;
    }

    protected Criterion(String condition, Object value, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.typeHandler = typeHandler;
      if (value instanceof List<?>) {
        this.listValue = true;
      } else {
        this.singleValue = true;
      }
    }

    protected Criterion(String condition, Object value) {
      this(condition, value, null);
    }

    protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
      super();
      this.condition = condition;
      this.value = value;
      this.secondValue = secondValue;
      this.typeHandler = typeHandler;
      this.betweenValue = true;
    }

    protected Criterion(String condition, Object value, Object secondValue) {
      this(condition, value, secondValue, null);
    }
  }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table role_permissions
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}