package io.github.xdiamond.domain;

import java.util.Date;
import java.io.Serializable;

public class User implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
   * @mbggenerated
   */
  private Integer id;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
   * @mbggenerated
   */
  private String name;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.nickName
   * @mbggenerated
   */
  private String nickName;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
   * @mbggenerated
   */
  private String password;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.passwordSalt
   * @mbggenerated
   */
  private String passwordSalt;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.email
   * @mbggenerated
   */
  private String email;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.createTime
   * @mbggenerated
   */
  private Date createTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.updateTime
   * @mbggenerated
   */
  private Date updateTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.lastLoginTime
   * @mbggenerated
   */
  private Date lastLoginTime;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.loginCount
   * @mbggenerated
   */
  private Integer loginCount;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user.provider
   * @mbggenerated
   */
  private String provider;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table user
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
   * @return  the value of user.id
   * @mbggenerated
   */
  public Integer getId() {
    return id;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
   * @param id  the value for user.id
   * @mbggenerated
   */
  public void setId(Integer id) {
    this.id = id;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
   * @return  the value of user.name
   * @mbggenerated
   */
  public String getName() {
    return name;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
   * @param name  the value for user.name
   * @mbggenerated
   */
  public void setName(String name) {
    this.name = name;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.nickName
   * @return  the value of user.nickName
   * @mbggenerated
   */
  public String getNickName() {
    return nickName;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.nickName
   * @param nickName  the value for user.nickName
   * @mbggenerated
   */
  public void setNickName(String nickName) {
    this.nickName = nickName;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
   * @return  the value of user.password
   * @mbggenerated
   */
  public String getPassword() {
    return password;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
   * @param password  the value for user.password
   * @mbggenerated
   */
  public void setPassword(String password) {
    this.password = password;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.passwordSalt
   * @return  the value of user.passwordSalt
   * @mbggenerated
   */
  public String getPasswordSalt() {
    return passwordSalt;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.passwordSalt
   * @param passwordSalt  the value for user.passwordSalt
   * @mbggenerated
   */
  public void setPasswordSalt(String passwordSalt) {
    this.passwordSalt = passwordSalt;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.email
   * @return  the value of user.email
   * @mbggenerated
   */
  public String getEmail() {
    return email;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.email
   * @param email  the value for user.email
   * @mbggenerated
   */
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.createTime
   * @return  the value of user.createTime
   * @mbggenerated
   */
  public Date getCreateTime() {
    return createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.createTime
   * @param createTime  the value for user.createTime
   * @mbggenerated
   */
  public void setCreateTime(Date createTime) {
    this.createTime = createTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.updateTime
   * @return  the value of user.updateTime
   * @mbggenerated
   */
  public Date getUpdateTime() {
    return updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.updateTime
   * @param updateTime  the value for user.updateTime
   * @mbggenerated
   */
  public void setUpdateTime(Date updateTime) {
    this.updateTime = updateTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.lastLoginTime
   * @return  the value of user.lastLoginTime
   * @mbggenerated
   */
  public Date getLastLoginTime() {
    return lastLoginTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.lastLoginTime
   * @param lastLoginTime  the value for user.lastLoginTime
   * @mbggenerated
   */
  public void setLastLoginTime(Date lastLoginTime) {
    this.lastLoginTime = lastLoginTime;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.loginCount
   * @return  the value of user.loginCount
   * @mbggenerated
   */
  public Integer getLoginCount() {
    return loginCount;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.loginCount
   * @param loginCount  the value for user.loginCount
   * @mbggenerated
   */
  public void setLoginCount(Integer loginCount) {
    this.loginCount = loginCount;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user.provider
   * @return  the value of user.provider
   * @mbggenerated
   */
  public String getProvider() {
    return provider;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user.provider
   * @param provider  the value for user.provider
   * @mbggenerated
   */
  public void setProvider(String provider) {
    this.provider = provider;
  }
}