package io.github.xdiamond.domain;

import java.io.Serializable;

public class UserGroup implements Serializable {

  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user_groups.userId
   * @mbggenerated
   */
  private Integer userId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user_groups.groupId
   * @mbggenerated
   */
  private Integer groupId;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database column user_groups.access
   * @mbggenerated
   */
  private Integer access;
  /**
   * This field was generated by MyBatis Generator. This field corresponds to the database table user_groups
   * @mbggenerated
   */
  private static final long serialVersionUID = 1L;

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user_groups.userId
   * @return  the value of user_groups.userId
   * @mbggenerated
   */
  public Integer getUserId() {
    return userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user_groups.userId
   * @param userId  the value for user_groups.userId
   * @mbggenerated
   */
  public void setUserId(Integer userId) {
    this.userId = userId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user_groups.groupId
   * @return  the value of user_groups.groupId
   * @mbggenerated
   */
  public Integer getGroupId() {
    return groupId;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user_groups.groupId
   * @param groupId  the value for user_groups.groupId
   * @mbggenerated
   */
  public void setGroupId(Integer groupId) {
    this.groupId = groupId;
  }

  /**
   * This method was generated by MyBatis Generator. This method returns the value of the database column user_groups.access
   * @return  the value of user_groups.access
   * @mbggenerated
   */
  public Integer getAccess() {
    return access;
  }

  /**
   * This method was generated by MyBatis Generator. This method sets the value of the database column user_groups.access
   * @param access  the value for user_groups.access
   * @mbggenerated
   */
  public void setAccess(Integer access) {
    this.access = access;
  }
}